var annotated_dup =
[
    [ "std", null, [
      [ "iterator_traits< stdgpu::device_ptr< T > >", "structstd_1_1iterator__traits_3_01stdgpu_1_1device__ptr_3_01T_01_4_01_4.html", "structstd_1_1iterator__traits_3_01stdgpu_1_1device__ptr_3_01T_01_4_01_4" ],
      [ "iterator_traits< stdgpu::host_ptr< T > >", "structstd_1_1iterator__traits_3_01stdgpu_1_1host__ptr_3_01T_01_4_01_4.html", "structstd_1_1iterator__traits_3_01stdgpu_1_1host__ptr_3_01T_01_4_01_4" ]
    ] ],
    [ "stdgpu", null, [
      [ "atomic", "classstdgpu_1_1atomic.html", "classstdgpu_1_1atomic" ],
      [ "atomic_ref", "classstdgpu_1_1atomic__ref.html", "classstdgpu_1_1atomic__ref" ],
      [ "back_insert_iterator", "classstdgpu_1_1back__insert__iterator.html", "classstdgpu_1_1back__insert__iterator" ],
      [ "bitset", "classstdgpu_1_1bitset.html", "classstdgpu_1_1bitset" ],
      [ "default_allocator_traits", "structstdgpu_1_1default__allocator__traits.html", null ],
      [ "deque", "classstdgpu_1_1deque.html", "classstdgpu_1_1deque" ],
      [ "device_range", "classstdgpu_1_1device__range.html", "classstdgpu_1_1device__range" ],
      [ "front_insert_iterator", "classstdgpu_1_1front__insert__iterator.html", "classstdgpu_1_1front__insert__iterator" ],
      [ "hash", "structstdgpu_1_1hash.html", "structstdgpu_1_1hash" ],
      [ "hash< bool >", "structstdgpu_1_1hash_3_01bool_01_4.html", "structstdgpu_1_1hash_3_01bool_01_4" ],
      [ "hash< char >", "structstdgpu_1_1hash_3_01char_01_4.html", "structstdgpu_1_1hash_3_01char_01_4" ],
      [ "hash< char16_t >", "structstdgpu_1_1hash_3_01char16__t_01_4.html", "structstdgpu_1_1hash_3_01char16__t_01_4" ],
      [ "hash< char32_t >", "structstdgpu_1_1hash_3_01char32__t_01_4.html", "structstdgpu_1_1hash_3_01char32__t_01_4" ],
      [ "hash< double >", "structstdgpu_1_1hash_3_01double_01_4.html", "structstdgpu_1_1hash_3_01double_01_4" ],
      [ "hash< float >", "structstdgpu_1_1hash_3_01float_01_4.html", "structstdgpu_1_1hash_3_01float_01_4" ],
      [ "hash< int >", "structstdgpu_1_1hash_3_01int_01_4.html", "structstdgpu_1_1hash_3_01int_01_4" ],
      [ "hash< long >", "structstdgpu_1_1hash_3_01long_01_4.html", "structstdgpu_1_1hash_3_01long_01_4" ],
      [ "hash< long double >", "structstdgpu_1_1hash_3_01long_01double_01_4.html", "structstdgpu_1_1hash_3_01long_01double_01_4" ],
      [ "hash< long long >", "structstdgpu_1_1hash_3_01long_01long_01_4.html", "structstdgpu_1_1hash_3_01long_01long_01_4" ],
      [ "hash< short >", "structstdgpu_1_1hash_3_01short_01_4.html", "structstdgpu_1_1hash_3_01short_01_4" ],
      [ "hash< signed char >", "structstdgpu_1_1hash_3_01signed_01char_01_4.html", "structstdgpu_1_1hash_3_01signed_01char_01_4" ],
      [ "hash< unsigned char >", "structstdgpu_1_1hash_3_01unsigned_01char_01_4.html", "structstdgpu_1_1hash_3_01unsigned_01char_01_4" ],
      [ "hash< unsigned int >", "structstdgpu_1_1hash_3_01unsigned_01int_01_4.html", "structstdgpu_1_1hash_3_01unsigned_01int_01_4" ],
      [ "hash< unsigned long >", "structstdgpu_1_1hash_3_01unsigned_01long_01_4.html", "structstdgpu_1_1hash_3_01unsigned_01long_01_4" ],
      [ "hash< unsigned long long >", "structstdgpu_1_1hash_3_01unsigned_01long_01long_01_4.html", "structstdgpu_1_1hash_3_01unsigned_01long_01long_01_4" ],
      [ "hash< unsigned short >", "structstdgpu_1_1hash_3_01unsigned_01short_01_4.html", "structstdgpu_1_1hash_3_01unsigned_01short_01_4" ],
      [ "hash< wchar_t >", "structstdgpu_1_1hash_3_01wchar__t_01_4.html", "structstdgpu_1_1hash_3_01wchar__t_01_4" ],
      [ "host_range", "classstdgpu_1_1host__range.html", "classstdgpu_1_1host__range" ],
      [ "insert_iterator", "classstdgpu_1_1insert__iterator.html", "classstdgpu_1_1insert__iterator" ],
      [ "mutex_array", "classstdgpu_1_1mutex__array.html", "classstdgpu_1_1mutex__array" ],
      [ "mutex_ref", "classstdgpu_1_1mutex__ref.html", "classstdgpu_1_1mutex__ref" ],
      [ "numeric_limits", "structstdgpu_1_1numeric__limits.html", null ],
      [ "queue", "classstdgpu_1_1queue.html", "classstdgpu_1_1queue" ],
      [ "safe_device_allocator", "structstdgpu_1_1safe__device__allocator.html", "structstdgpu_1_1safe__device__allocator" ],
      [ "safe_managed_allocator", "structstdgpu_1_1safe__managed__allocator.html", "structstdgpu_1_1safe__managed__allocator" ],
      [ "safe_pinned_host_allocator", "structstdgpu_1_1safe__pinned__host__allocator.html", "structstdgpu_1_1safe__pinned__host__allocator" ],
      [ "sizediv_t", "structstdgpu_1_1sizediv__t.html", "structstdgpu_1_1sizediv__t" ],
      [ "stack", "classstdgpu_1_1stack.html", "classstdgpu_1_1stack" ],
      [ "transform_range", "classstdgpu_1_1transform__range.html", "classstdgpu_1_1transform__range" ],
      [ "unordered_map", "classstdgpu_1_1unordered__map.html", "classstdgpu_1_1unordered__map" ],
      [ "unordered_set", "classstdgpu_1_1unordered__set.html", "classstdgpu_1_1unordered__set" ],
      [ "vector", "classstdgpu_1_1vector.html", "classstdgpu_1_1vector" ]
    ] ]
];